@startuml
left to right direction
actor Admin
actor Coordenador
actor Professor
actor Aluno

rectangle "Sistema Colégio Mara e Lu" {
  usecase "UC01 Login" as UC01
  usecase "UC02 Inscrição pública" as UC02
  usecase "UC03 Gerir inscrições" as UC03
  usecase "UC04 Gerir utilizadores" as UC04
  usecase "UC06 Académico" as UC06
  usecase "UC09 Lançar notas" as UC09
  usecase "UC10 Alterar notas" as UC10
  usecase "UC12 Portal notas" as UC12
  usecase "UC13 Faltas" as UC13
  usecase "UC15 Materiais" as UC15
  usecase "UC17 Perfil" as UC17
}

Admin --> UC04
Admin --> UC06
Admin --> UC10
Coordenador --> UC03
Coordenador --> UC06
Coordenador --> UC10
Professor --> UC01
Professor --> UC09
Professor --> UC13
Professor --> UC15
Aluno --> UC01
Aluno --> UC12
Aluno --> UC17
UC10 ..> UC09 : extend
@enduml
